---
title: "Permiting and Inspection Times"
author: "Russel Willems and Adam Elder"
date: "1/22/2020"
output: 
    html_document:
        toc: true
        code_folding: hide
        toc_depth: 2
        toc_float: true
        number_sections: true
---

```{r set_opts}
knitr::opts_chunk$set(warning = FALSE, echo = FALSE, message = FALSE)
```

```{r read_in_data}
library("wesanderson")
library("tidyverse")
library("DescTools")
library("ggplot2")
library("cowplot")
theme_set(theme_cowplot())

d <- read.csv("expanded_dat.csv", stringsAsFactors = FALSE)

d$ap_date <- as.Date(d$Application.Completed.Date..1,
                     "%m/%d/%Y")
d$pi_date <- as.Date(d$Permit.Issued.Date..1,
                     "%m/%d/%Y")
d$ic_date <- as.Date(d$Inspections.Completed.Date..1,
                     "%m/%d/%Y")

d <- d[order(d$ap_date, decreasing = FALSE), ]
long <- d
d <- d[-(1:10), ]
d <- d[!is.na(d$ap_date), ]


make_some_lines <- function(row, num){
  app_done <- as.numeric(row["ap_date"])
  perm_prv <- as.numeric(row["pi_date"])
  inspec   <- as.numeric(row["ic_date"])
  if(is.na(perm_prv)){
    if(!is.na(app_done)){
      lines(x = c(app_done, app_done + 1),
            y = rep(num, 2), col = "blue")
    }
  }else{
    if(!is.na(app_done)){
      lines(x = c(app_done, perm_prv),
            y = rep(num, 2),
            col = "blue")
    }
  }
  if(is.na(inspec)){
    if(!is.na(perm_prv)){
      lines(x = c(perm_prv, perm_prv + 1),
            y = rep(num, 2),
             col = "red")
    }
  }else{
    if(!is.na(app_done)){
      lines(x = c(perm_prv, inspec),
            y = rep(num, 2),
            col = "red")
    }
  }
}
```


# Time from Application to Aproval

```{r ap_to_aprov}
d$d_diff <- difftime(d$pi_date, d$ap_date, units = "day")
d$d_diff_ic <- difftime(d$ic_date, d$pi_date, units = "day")
d$l_tdiff <- pmax(0, log(as.numeric(d$d_diff)))
d$un_grp <- cut(d$HousingUnits,  
                unique(quantile(d$HousingUnits, seq(0, 1, length.out = 40))),
                include.lowest = TRUE)

ap_hist <- ggplot(d) + aes(x = d_diff) +
  geom_histogram(bins = 30) +
  xlab("Time in Days from Application to Aproval") + 
  geom_vline(aes(xintercept = mean(d$d_diff, na.rm = TRUE)), col = "red",
             size = 2) + 
  annotate("text", x = mean(d$d_diff, na.rm = TRUE) + 10, y = 350,
           label = paste0("Mean Value : ", round(mean(d$d_diff, na.rm = TRUE))),
           col = "red", hjust = 0, size = 7) + 
  geom_vline(aes(xintercept = median(d$d_diff, na.rm = TRUE)), col = "blue",
             size = 2) + 
  annotate("text", x = mean(d$d_diff, na.rm = TRUE) + 10, y = 200,
           label = paste0("Median Value : ", round(median(d$d_diff, na.rm = TRUE))),
           col = "blue", hjust = 0, size = 7)


ap_hist

ggplot(d) + aes(x = un_grp, y = d_diff) + geom_boxplot() + ylab("Time in Days from Application to Aproval") + xlab("Number Housing Units") + 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1)
```

# Time from Aproval to Inspections

```{r aprov_to_inspec}
# ggplot(d) + aes(x = d_diff_ic) + geom_histogram() + xlab("Time in Days from Aproval to Inspection completion")

ic_hist <- ggplot(d) + aes(x = d_diff_ic) +
  geom_histogram(bins = 30) +
  xlab("Time in Days from Application to Aproval") + 
  geom_vline(aes(xintercept = mean(d$d_diff_ic, na.rm = TRUE)), col = "red",
             size = 2) + 
  annotate("text", x = mean(d$d_diff_ic, na.rm = TRUE) + 40, y = 50,
           label = paste0("Mean Value : ", round(mean(d$d_diff_ic, na.rm = TRUE))),
           col = "red", hjust = 0, size = 7) + 
  geom_vline(aes(xintercept = median(d$d_diff_ic, na.rm = TRUE)), col = "blue",
             size = 2) + 
  annotate("text", x = mean(d$d_diff_ic, na.rm = TRUE) + 10, y = 25,
           label = paste0("Median Value : ", round(median(d$d_diff_ic, na.rm = TRUE))),
           col = "blue", hjust = 0, size = 7)
ic_hist

ggplot(d) + aes(x = un_grp, y = d_diff_ic) + geom_boxplot() + ylab("Time in Days from Aproval to Inspection") + xlab("Number Housing Units") + 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1)
```


# Fun Line Plot

Each horrizontal line is a single project.  The blue part of the line is the time from the application being completed to the permit being issued.  The red line is the time from the permit being issued to the inspections being completed.

```{r fun_line_plot}
bounds <- c(d$ap_date[1], max(c(d$pi_date, d$pi_date,
                                 d$ic_date), na.rm = TRUE))

plot(bounds, c(nrow(d), 1), type = "b", col = "white",
     bty = "n", ylab = "Observation Number",
     "xlab" = "Date", axes = FALSE)
some_dates <- seq(from = bounds[1], to = bounds[2], length.out = 40)
axis(1, at = some_dates, labels = format(some_dates, "%Y-%m"))
for(bb in 1:nrow(d)){
  make_some_lines(d[bb, ], nrow(d) - bb)
}
```







