
# Future Work {#future}

## NSFG / High-risk population
See Issue [#94](https://github.com/statnet/SHAMP/issues/94). Martina noted that data cannot be combined in ergm.ego until the formats are similar for the stats for ERGM.

## Modelling immigrant spouses who live in home country
See Issue [#151](https://github.com/statnet/SHAMP/issues/151).

## Life expectancy for HIV + 
Issue [#60](https://github.com/statnet/SHAMP/issues/60) links to a paper on "Population-Based Estimates of Life Expectancy After HIV Diagnosis: United States 2008-2011".

## Nodematched Cohabs too low for B/BI/H/HI

See Issues [#149](https://github.com/statnet/SHAMP/issues/149) and the comment Martina made in the Diagnostics Sept 2018 model run in Issue [#146](https://github.com/statnet/SHAMP/issues/146#issuecomment-424153331). See the [Model Cohab section](#cohaberg) to see how the terms plateau low - they also were low in the Spring 2019 models.


## Age related within and cross-net concurrency

Focusing on an agecat3 x deg.pers interaction would be worth exploring in the future  (Issue [#102](https://github.com/statnet/SHAMP/issues/102)).

## Removing alters with missing data

Currently - 5% of nodes are missing information on age (See Issue [#120](https://github.com/statnet/SHAMP/issues/120)). 

This raised an issue of deleting alters to get the ergms to run. Jeanette wants to explore if there are problems with missing data and dropping alters on the initial network. Full discussion of this, and consequences for WHAMP are explored in Issue [#62](https://github.com/statnet/SHAMP/issues/62).


## Add 10 year death rate data

See [Issue #61](https://github.com/statnet/SHAMP/issues/61).


## Simulation run limitations

There was a twofold limitation in running the simulations, and will be passed on for future work:

1) the High Performance Cluster schedulers (HYAK) on the UW servers were upgraded in the past year to the SLURM scheduler. Due to these changes, there have a number of modifications that were made. This will require more time to properly navigate the newer generation of Hyak.

2) To incorporate Approximate Bayesian Computations (ABC) to the simulation runs, we rely on the EpiABC package. This package outputs parameters that are expected to converge and approximate the expected prevalence, but there have been several problems in the package. We will manually investigate paramter spaces to approximate prevalence, and will use ABC for future work. See Issues [#89](https://github.com/statnet/SHAMP/issues/89) for ABC targets, [#171](https://github.com/statnet/SHAMP/issues/171) ABC priors, and [#90](https://github.com/statnet/SHAMP/issues/90)  ABC levers.

Microbenching the project would also showcase areas that are holding back the process, as shown in Issue [#154](https://github.com/statnet/SHAMP/issues/154), and this will be pursued for future work. 

## Dynamic EpiModel Parameter application

The current workflow for applying modelling parameters to the simulations is by hardcoding the values into the code. Some work has been made to automate this process by recording the values and the source of the parameter data into an Excel sheet. This work is recorded under https://github.com/statnet/EpiModelHIV/blob/shamp_params/data/Model%20Parameters.Sara.work.xlsx and is under the `shamp_params` branch in EpiModelHIV. The parameters have been added to the `statnet/EpiModelHIV/R/params.shamp.R` file.

Future work will be to test the entire EpiModelHIV with the parameters included in new params.shamp.R code.
